'use client'

import React, { useState } from "react";
import Sidebar from './Sidebar'
import Link from "next/link"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBars } from '@fortawesome/free-solid-svg-icons'

const metadata = {
  title: 'SAKILA',
  description: 'Generated by create next app',
}

export default function Header() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const handleMenuClick = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return <header>
    <nav className="bg-slate-950 p-3 flex flex-row">
      <h1 className="text-slate-100 text-left">
        {metadata.title}
      </h1>
      <button
        className="text-slate-100 hover:text-slate-300 ml-auto"
        onClick={handleMenuClick}
      >
        <FontAwesomeIcon icon={faBars} />
      </button>
    </nav>
    <Sidebar isOpen={isSidebarOpen} onClose={() => setIsSidebarOpen(false)} />
  </header>
}